[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode.workspace = true
common.path = "../common"
clap.workspace = true
crossterm = "0.25.0"
nalgebra.workspace = true
serde.workspace = true
winterm = "0.6.0"
image = "0.24.4"
